### ISSUE TITLE
PHPMYADMIN_HASH is needed by compile stage

### ISSUE THREAD

**Issue by jyriok** [cloudfoundry-samples/cf-ex-phpmyadmin#21]
if PHPMYADMIN_HASH is not set, we have this error :

 ```
  Installing PHPMyAdmin 5.1.1
   Traceback (most recent call last):
     File "/tmp/buildpacks/8c23692cf1ba7ed1650dd13082f80f9d/scripts/compile.py", line 59, in <module>
       .from_build_pack('lib/additional_commands')
     File "/tmp/buildpacks/8c23692cf1ba7ed1650dd13082f80f9d/lib/build_pack_utils/builder.py", line 212, in extensions
       process_extension(path, ctx, 'compile', process, args=[self])
     File "/tmp/buildpacks/8c23692cf1ba7ed1650dd13082f80f9d/lib/build_pack_utils/utils.py", line 69, in process_extension
       success(getattr(extn, to_call)(*args))
     File "/tmp/app/.extensions/phpmyadmin/extension.py", line 42, in compile
       DEFAULTS['PHPMYADMIN_HASH'],
     File "/tmp/buildpacks/8c23692cf1ba7ed1650dd13082f80f9d/lib/build_pack_utils/utils.py", line 151, in __getitem__
       return self.format(dict.__getitem__(self, key))
   KeyError: 'PHPMYADMIN_HASH'
   Failed to compile droplet: Failed to run finalize script: exit status 1


```

**Comment by dmikusa** [comment]
I think that should fix the issue. Reopen and let me know if you're still seeing trouble. Sorry about that.
